kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

volumes:
  - name: cache
    host:
      path: /var/docker/drone-github/cache/gomod


steps:
#  - name: build
#    image: golang:latest
#    volumes:
#      - name: cache
#        path: /go/pkg/mod
#    commands:
#      - apt-get --allow-insecure-repositories update
#      - apt-get install -y libc6-dev libc-dev make mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget
#      - git submodule update --init --recursive
#      - make -C extern/filecoin-ffi
#      - go mod download
#      - buildflags="-X 'main.BuildTime=`TZ=\"Asia/Shanghai\" date -Iseconds`' -X 'main.GitMessage=`git --no-pager log -1 --oneline`' -X 'main.GoVersion=$(go version)'" && go build -ldflags "$buildflags" -o go-bin
#      - ./go-bin

  - name: docker-build-push
    image: plugins/docker
    volumes:
      - name: cache
        path: /go/pkg/mod
    when:
      branch:
        - master
    settings:
      repo: cloverzrg/filecoin-wallet
      tags: latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password